### ISSUE TITLE
[Bug]: can only listen on one address or all addresses

### ISSUE THREAD

**Issue by smoser** [project-zot/zot#1063]
### zot version

v1.4.3-0-g69f0cf6

### Describe the bug

I wanted to run a zot thatlistened on localhost and also on an existing IP address.
It seems there is no way to accomplish that.

You can do:
 * single address with 'address: ip.or.hostname.here`
 * all interfaces with `address: ""` (this is quite non-obvious, not documented and does *not* have this behavior if you leave 'address' out entirely).

But you can't list a set of interfaces or ip to listen on.

### To reproduce

1. Configuration

```yaml
http:
  #address: "10.0.0.2"
  address: ""
  port: 5000
  realm: zot
  auth:
    htpasswd:
      path: htpasswd.txt
log:
  level: debug
  audit: logs/audit.log
  output: logs/zot.log
storage:
  rootdirectory: storage
```

2. Client tool used: telnet
3. Seen error: connection refused.

### Additional context

Maybe there is a common way to do this , but I'm missing it. This could just be 'user' error.
