### ISSUE TITLE
[Feat]: sync specific images from docker hub

### ISSUE THREAD

**Issue by smoser** [project-zot/zot#1064]
### Is your feature request related to a problem? Please describe.

I want to sync (extensions/sync) a specific list of images from docker humb.
Example:
 * ubuntu:jammy
 * ubuntu:focal
 * alpine:edge
 * centos:latest

I am not interested in a caching-proxy-like behavior (onDemand: true).  
I was hoping I could do something like:

```yaml
extensions:
  sync:
    enable: true
    registries:
      - urls: ["https://docker.io/library"]
        onDemand: false
        pollInterval: 12h
        tlsVerify: true
        content:
          - name: ubuntu:jammy
            destination: /sync
```

And then run:

```
skopeo copy docker://localhost:5000/sync/ubuntu:jammy oci:/tmp/oci.d:ubuntu:jammy
```

I guess the main problem I have with caching-proxy against docker is the bandwidth limit.  I want to be explicit.
