### ISSUE TITLE
[Want help]: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by jsparter** [project-zot/zot#1221]
### zot version

v1.4.3

### Describe the bug

I want to run zot in a single docker as follow:
```
docker run -d -p 5000:5000 \
--restart=always \
-v $certs:/certs \
-v $registry:/var/lib/registry \
-v $config/config.yaml:/etc/zot/config.yaml \
-v $htpasswd/htpasswd:/etc/zot/htpasswd \
ghcr.io/project-zot/zot-linux-amd64:v1.4.3
```
Then I follow user guide to test pull and push commands.
I found that almost all Client have disable tls except helm, and I encountered an error when I execute `helm push`  :
```
# helm push zot-0.1.17.tgz oci://localhost:5000/zot-chart
Error: failed to do request: Head "https://localhost:5000/v2/zot-chart/zot/blobs/sha256:8c5a2f7e060de18eda9220fe31e6bcd6ec624e9a6321e4594524eff0ec84945b": http: server gave HTTP response to HTTPS client
```
Then I try to use skopeo、podman to pull images as follows, and all of them return same error `http: server gave HTTP response to HTTPS client`:
```
podman pull --cert-dir $certs localhost:5000/alpine:3.13
podman pull --creds xxxx:xxxx localhost:5000/alpine:3.13
skopeo inspect --creds=sealer:sealer docker://localhost:5000/alpine:3.13
skopeo inspect --cert-dir=$certs docker://localhost:5000/alpine:3.13
skopeo copy --dest-creds=xxxx:xxxx docker-daemon:alpine:3.13 docker://localhost:5000/alpine:3.13
skopeo copy --dest-cert-dir=$certs docker-daemon:alpine:3.13 docker://localhost:5000/alpine:3.13
```
I there any wrong with me?  I need immediate help!

### To reproduce

1. Configuration

```
distspecversion: 1.0.1-dev
http:
  address: 127.0.0.1
  auth:
    faildelay: 5
    htpasswd:
      path: /etc/zot/htpasswd
  port: 5000
  realm: zot
  tls:
    cert: /cert/zot.crt
    key: /cert/zot.key
storage:
  rootdirectory: /var/lib/registry
```
```
docker run -d -p 5000:5000 \
--restart=always \
-v $certs:/certs \
-v $registry:/var/lib/registry \
-v $config/config.yaml:/etc/zot/config.yaml \
-v $htpasswd/htpasswd:/etc/zot/htpasswd \
ghcr.io/project-zot/zot-linux-amd64:v1.4.3
```
2. Client tool used

3. Seen error

### Expected behavior

all actions work well
