### ISSUE TITLE
[Feat]: support read-only access with more than anonymousPolicy

### ISSUE THREAD

**Issue by smoser** [project-zot/zot#1679]
### Is your feature request related to a problem? Please describe.

I'd like to run a zot that serves up a read-only RootDirectory but does not allow anonymous access.
I was able to start a zot (did not test significantly) pointing it at a read-only mount with this config:

```yaml
distspecversion: 1.1.0-dev
storage:
  rootdirectory: /tmp/myzotd
  dedupe: false
  remotecache: false
  gc: false
  commit: false
http:
  address: 127.1.1.1
  port: "0"
  accesscontrol:
    repositories:
      '**':
        anonymousPolicy: [read]
  realm: zot
log:
  level: debug
  output: logs/access.log
  audit: logs/audit.log
```

But I would like to be able to use a config below.  The changes from above are:
 * htpasswd auth
 * anonymous does not have read permission
 * default permission is none
 * the 'ro-user' has explicit 'read' permission.

```yaml
distspecversion: 1.1.0-dev
storage:
  rootdirectory: /tmp/myzotd
  dedupe: false
  remotecache: false
  gc: false
  commit: false
http:
  address: 127.1.1.1
  port: 0
  auth:
    htpasswd:
      path: htpasswd
  accesscontrol:
    repositories:
      '**':
        anonymousPolicy: []
        defaultPolicy: []
        policies:
          - users: ["ro-user"]
            actions: ["read"]
  realm: zot
log:
  level: debug
  output: logs/access.log
  audit: logs/audit.log
```

An attempt will currently fail like this:
```
$ ./zot-linux-amd64-minimal --version 2>&1 | jq
{
  "level": "info",
  "distribution-spec": "1.1.0-dev",
  "commit": "v2.0.0-rc6-0-gde24bd9",
  "binary-type": "minimal",
  "go version": "go1.20.6",
  "time": "2023-08-04T14:24:24-07:00",
  "message": "version"
}

$ ./zot-linux-amd64-minimal serve config.yaml 
panic: open /tmp/myzotd/repo.db: read-only file system

goroutine 1 [running]:
zotregistry.io/zot/pkg/cli.newServeCmd.func1(0xc000e7e000?, {0xc00024bcc0, 0x1, 0x1?})
        zotregistry.io/zot/pkg/cli/root.go:66 +0x11f
github.com/spf13/cobra.(*Command).execute(0xc000e7e000, {0xc00024bc80, 0x1, 0x1})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xc000b11b00)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
        github.com/spf13/cobra@v1.7.0/command.go:992 +0x19
main.main()
        zotregistry.io/zot/cmd/zot/main.go:10 +0x1e
```

**Comment by andaaron** [comment]
Hi @smoser, are you sure zot can write to the folder set as root directory? It looks like it failed to create the db (the one it uses to store the groups the user may belong to, among other things). Opening that file is triggered by you enabling user authentication.

**Comment by smoser** [comment]
I got something working that is I think sufficient for me using a "/" subPath:

```yaml
storage:
  rootdirectory: "/path/to/writable/dir"
  dedupe: false
  remotecache: false
  gc: false
  commit: false
  subpaths:
    "/":
      rootdirectory: "/path/to/read-only/dir"
```

The files/directories listed above are written into /path/to/writable/dir
(repo.db and friends) and /path/to/read-only/dir is unmodified.

Attached ([go-test.sh.txt](https://github.com/project-zot/zot/files/12283448/go-test.sh.txt)) is a script that demonstrates this working. It takes as input a "top dir" and a "orig dir".  config is written into top_dir, a read-only bind-mount of orig-dir is done to top_dir/ro-data and that directory is used for the subPath.

The whole config looks something like this:
```yaml
distspecversion: 1.1.0-dev
storage:
  rootdirectory: "/tmp/td/testd/rootDir"
  dedupe: false
  remotecache: false
  gc: false
  commit: false
  subPaths:
    "/":
      rootDirectory: "/tmp/td/testd/ro-data"
http:
  address: "127.1.1.1"
  port: 0
  auth:
    htpasswd:
      path: "/tmp/td/testd/htpasswd"
  accesscontrol:
    repositories:
      '**':
        anonymousPolicy: []
        defaultPolicy: []
        policies:
          - users: ["ro-user"]
            actions: ["read"]
  realm: zot
log:
  level: debug
  output: "/tmp/td/testd/access.log"
  audit: "/tmp/td/testd/audit.log"
```
