### ISSUE TITLE
[Bug]: Can't get htpassword auth working

### ISSUE THREAD

**Issue by Moosemorals** [project-zot/zot#1836]
### zot version

v2.0.0-rc6-de24bd937f20a66628fdacf4d658eb95df0b3769

### Describe the bug

I've setup htpasswd auth per the v2 docs (I think!), but the k8s ready/live probes are failing with 401 errors

### To reproduce

1. Configuration
Helm chart for install:
```yaml
service:
  type: ClusterIP
persistence: true
pvc:
  create: false
  name: images
httpGet:
  scheme: HTTPS
mountConfig: true
externalSecrets:
  - secretName: "registry-mtls"
    mountPath: "/certs"

configFiles:
  config.json: |-
    {
      "extensions": {
        "scrub": {
          "interval": "23h"
        }
      },
      "storage": {
        "rootDirectory": "/var/lib/registry",
        "dedupe": true,
        "gc": true
      },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "auth": {
          "htpasswd": {
            "path": "/secret/htpasswd"
          }
        },
        "tls": {
          "cert": "/certs/tls.crt",
          "key": "/certs/tls.key"
        },
        "accessControl": {
          "repositories": {
            "**": {
              "policies": [{
                "users": ["k8s"],
                "actions":["read"]
              }]
            }
          },
          "adminPolicy": {
            "users": [ "admin" ],
            "actions": [ "read", "create", "update", "delete" ]
          }
        }
      },
      "log": {
        "level": "debug"
      }
    }
mountSecret: true
secretFiles:
  htpasswd: |-
    user:$2y$05$yE07lhelZYRVpv2OTieb1utN5zloGLgml7Y4gc5gOW.em2M35sVou
    admin:$2y$05$uMec3ips2C/GZqCSaF/gl.XgoK1.i2zeqGnxV6BvwBXRvy94FUYza
    k8s:$2y$05$bQHc9W7ZvvJuAda2i24QVul8eeDNa67V.oPWVMTK898FZHL4CpMGW

authHeader: azhzOmRpcmVjdGx5Zml2ZWVtcHR5c2NvcmUK
```

2. Wait for helm install to run
3. View the k8s log
4. See error (formatted)
```json
{
  "level": "info",
  "module": "http",
  "username": "k8s",
  "clientIP": "10.72.0.1:50852",
  "method": "GET",
  "path": "/v2/",
  "statusCode": 401,
  "latency": "0s",
  "bodySize": 283,
  "headers": {
    "Accept": [
      "*/*"
    ],
    "Authorization": [
      "******"
    ],
    "User-Agent": [
      "kube-probe/1.27"
    ]
  },
  "goroutine": 51,
  "caller": "zotregistry.io/zot/pkg/api/session.go:131",
  "time": "2023-09-20T20:36:44.49492641Z",
  "message": "HTTP API"
}
```

### Expected behavior

I expected the live/ready checks to work

### Additional context

The htpasswd file and the authHeader were created with a simple script:
```sh
#!/bin/sh

htpasswd -bBn user fortbasealikeangry
htpasswd -bBn admin slabsrailroadwantvillage
htpasswd -bBn k8s directlyfiveemptyscore

echo "k8s:directlyfiveemptyscore" | base64
```
