### ISSUE TITLE
[Bug]: session cleanup with file system storage

### ISSUE THREAD

**Issue by aritas1** [project-zot/zot#1910]
### zot version

v2.0.0-rc6

### Describe the bug

After running rc6 for ~2 months now i found aporx. 4.3 million session stored on disk, blocking around 16GB.

### To reproduce

image: ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc6

config.yaml
```
distspecversion: 1.1.0-dev
http:
  address: 0.0.0.0
  port: 8080
  # externalUrl: "https://registry.example.com"  # as of v2.0.0-rc7
  #realm: zot
  auth:
    #faildelay: 5
    faildelay: 1
    htpasswd:
      path: /config/htpasswd
    openid:
      providers:
        dex:
          issuer: "https://sso.zitadel.com"
          clientid: zot@zitadel
          clientsecret: secret
          scopes:
          - openid
          - email
  accessControl:
    adminPolicy:
      users:
      - admin
      actions:
      - read
      - create
      - update
      - delete
      - detectManifestCollision
    repositories:
      "**":
        defaultPolicy:
        - read
        - create
log:
  level: info
storage:
  rootdirectory: /data/zot
  dedupe: true
  gc: true
extensions:
  metrics:
    enable: true
    prometheus:
      path: "/metrics_silly"
  search:
    enable: true
    cve:
      updateInterval: 24h
  ui:
    enable: true
  mgmt:
    enable: true
```

### Expected behavior

It would be nice if (expired) sessions can be deleted automatically and session duration can be configured.
