### ISSUE TITLE
[Bug]: delay on auth testing

### ISSUE THREAD

**Issue by aritas1** [project-zot/zot#1914]
### zot version

v2.0.0-rc6

### Describe the bug

My Watchtower clients (see [source](https://github.com/containrrr/watchtower/blob/284066a39d083fe4865ae43119a41b42d450b178/pkg/registry/auth/auth.go#L151)) and one of my docker/24.0.6 machines are probing the `/v2/` endpoint for every manifest request to see if an authentication is required.
With the the defaut settings, these requests get delayed for 5 seconds, so pulling layers gets very slow.

Some logs (note the lower latency due to my config):
```
zot-zot-1  | {"level":"error","error":"auth: failed parsing authorization header","goroutine":265496,"caller":"zotregistry.io/zot/pkg/api/authn.go:137","time":"2023-10-09T19:02:26.244222203Z","message":"failed to parse authorization header"}
zot-zot-1  | {"level":"info","module":"http","clientIP":"172.16.0.33:56702","method":"GET","path":"/v2/","statusCode":401,"latency":"1s","bodySize":283,"headers":{"Accept":["*/*"],"Accept-Encoding":["gzip"],"Connection":["close"],"User-Agent":["Watchtower (Docker)"],"X-Forwarded-For":["::ffff:xx.xx.xx.xx"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["::ffff:xx.xx.xx.xx"]},"goroutine":265496,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-10-09T19:02:27.244453749Z","message":"HTTP API"}
zot-zot-1  | {"level":"info","identity":"nas","goroutine":265498,"caller":"zotregistry.io/zot/pkg/api/authn.go:177","time":"2023-10-09T19:02:27.413767392Z","message":"user profile successfully set"}
zot-zot-1  | {"level":"info","module":"http","username":"nas","clientIP":"172.16.0.33:56704","method":"HEAD","path":"/v2/xxx/xxx/app/manifests/latest","statusCode":200,"latency":"0s","bodySize":0,"headers":{"Accept":["application/vnd.docker.distribution.manifest.v2+json","application/vnd.docker.distribution.manifest.list.v2+json","application/vnd.docker.distribution.manifest.v1+json","application/vnd.oci.image.index.v1+json"],"Authorization":["******"],"Connection":["close"],"User-Agent":["Watchtower/1.5.3"],"X-Forwarded-For":["::ffff:xx.xx.xx.xx"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["::ffff:xx.xx.xx.xx"]},"goroutine":265498,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-10-09T19:02:27.414175814Z","message":"HTTP API"}

zot-zot-1  | {"level":"error","error":"auth: failed parsing authorization header","goroutine":266910,"caller":"zotregistry.io/zot/pkg/api/authn.go:137","time":"2023-10-09T19:27:24.716354518Z","message":"failed to parse authorization header"}
zot-zot-1  | {"level":"info","module":"http","clientIP":"172.16.0.33:58698","method":"GET","path":"/v2/","statusCode":401,"latency":"1s","bodySize":283,"headers":{"Accept-Encoding":["gzip"],"Connection":["close"],"User-Agent":["docker/24.0.6 go/go1.20.7 git-commit/1a79695 kernel/5.15.0-86-generic os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.6 \\(linux\\))"],"X-Forwarded-For":["xxxx:xxx:xxx:1225::2"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["xxxx:xxx:xxx:1225::2"]},"goroutine":266910,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-10-09T19:27:25.71698602Z","message":"HTTP API"}
zot-zot-1  | {"level":"info","module":"http","username":"vm2","clientIP":"172.16.0.33:58700","method":"HEAD","path":"/v2/xxx/yyyy/run/manifests/latest","statusCode":200,"latency":"0s","bodySize":0,"headers":{"Accept":["application/vnd.docker.distribution.manifest.v1+prettyjws","application/json","application/vnd.oci.image.manifest.v1+json","application/vnd.docker.distribution.manifest.v2+json","application/vnd.docker.distribution.manifest.list.v2+json","application/vnd.oci.image.index.v1+json"],"Authorization":["******"],"Connection":["close"],"User-Agent":["docker/24.0.6 go/go1.20.7 git-commit/1a79695 kernel/5.15.0-86-generic os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.6 \\(linux\\))"],"X-Forwarded-For":["xxxx:xxx:xxx:1225::2"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["xxxx:xxx:xxx:1225::2"]},"goroutine":266873,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-10-09T19:27:25.817923267Z","message":"HTTP API"}
```

I would propose waive the delay on requests without an Authorization header since the client is not probing credentials.

### To reproduce

image: ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc6

config.yaml

```
distspecversion: 1.1.0-dev
http:
  address: 0.0.0.0
  port: 8080
  # externalUrl: "https://registry.example.com"  # as of v2.0.0-rc7
  #realm: zot
  auth:
    #faildelay: 5
    faildelay: 1
    htpasswd:
      path: /config/htpasswd
    openid:
      providers:
        dex:
          issuer: "https://sso.zitadel.com"
          clientid: zot@zitadel
          clientsecret: secret
          scopes:
          - openid
          - email
  accessControl:
    adminPolicy:
      users:
      - admin
      actions:
      - read
      - create
      - update
      - delete
      - detectManifestCollision
    repositories:
      "**":
        defaultPolicy:
        - read
        - create
log:
  level: info
storage:
  rootdirectory: /data/zot
  dedupe: true
  gc: true
extensions:
  metrics:
    enable: true
    prometheus:
      path: "/metrics_silly"
  search:
    enable: true
    cve:
      updateInterval: 24h
  ui:
    enable: true
  mgmt:
    enable: true

```

**Comment by aritas1** [comment]
Quite an interesting question that crossed my mind at the time of creating the issue.

My config was cleand and did contain the following comment:
```
  accessControl:
    repositories:
      "**":
        defaultPolicy:
        - read
        - create
#      "public/**":
#        # this is bugy and will be fixed in 2.0.0-RC7+ see: PR #1647 & #1662
#        anonymousPolicy:
#        - read
```

I tested the flow with a partial public registry by enabling the anonymousPolicy config part for a sub path.

The result is that im not longer able to pull private images.
`/2/` returns a 200 and my docker 24.0.6 clients woun't send any Authorization headers for subsequent requests.

Here the some logs:
```
zot_testing-zot-1  | {"level":"info","module":"http","clientIP":"172.16.0.33:44608","method":"GET","path":"/v2/","statusCode":200,"latency":"0s","bodySize":0,"headers":{"Accept-Encoding":["gzip"],"Connection":["close"],"User-Agent":["docker/24.0.6 go/go1.20.7 git-commit/1a79695 kernel/5.4.0-164-generic os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.6 \\(linux\\))"],"X-Forwarded-For":["xx:xx:xx:xx:20::bd"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["xx:xx:xx:xx:20::bd"]},"goroutine":321,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-10-10T09:11:00.324885263Z","message":"HTTP API"}
zot_testing-zot-1  | {"level":"info","module":"http","clientIP":"172.16.0.33:44618","method":"HEAD","path":"/v2/xxxx/yyyy/app/manifests/latest","statusCode":403,"latency":"1s","bodySize":191,"headers":{"Accept":["application/json","application/vnd.oci.image.manifest.v1+json","application/vnd.docker.distribution.manifest.v2+json","application/vnd.docker.distribution.manifest.list.v2+json","application/vnd.oci.image.index.v1+json","application/vnd.docker.distribution.manifest.v1+prettyjws"],"Connection":["close"],"User-Agent":["docker/24.0.6 go/go1.20.7 git-commit/1a79695 kernel/5.4.0-164-generic os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.6 \\(linux\\))"],"X-Forwarded-For":["xx:xx:xx:xx:20::bd"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["xx:xx:xx:xx:20::bd"]},"goroutine":323,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-10-10T09:11:01.408893106Z","message":"HTTP API"}
zot_testing-zot-1  | {"level":"info","module":"http","clientIP":"172.16.0.33:44634","method":"GET","path":"/v2/xxxx/yyyy/app/manifests/latest","statusCode":403,"latency":"1s","bodySize":191,"headers":{"Accept":["application/json","application/vnd.oci.image.manifest.v1+json","application/vnd.docker.distribution.manifest.v2+json","application/vnd.docker.distribution.manifest.list.v2+json","application/vnd.oci.image.index.v1+json","application/vnd.docker.distribution.manifest.v1+prettyjws"],"Accept-Encoding":["gzip"],"Connection":["close"],"User-Agent":["docker/24.0.6 go/go1.20.7 git-commit/1a79695 kernel/5.4.0-164-generic os/linux arch/amd64 UpstreamClient(Docker-Client/24.0.6 \\(linux\\))"],"X-Forwarded-For":["xx:xx:xx:xx:20::bd"],"X-Forwarded-Port":["443"],"X-Forwarded-Proto":["https"],"X-Real-Ip":["xx:xx:xx:xx:20::bd"]},"goroutine":306,"caller":"zotregistry.io/zot/pkg/api/session.go:131","time":"2023-10-10T09:11:02.504488912Z","message":"HTTP API"}
```

This is a new problem in my view, i'm opening a new issue for that.
