### ISSUE TITLE
[Bug]: Kubernetes deployment does not respect http*_proxy environment variables

### ISSUE THREAD

**Issue by Kortekaasy** [project-zot/zot#1916]
### zot version

v.1.4.3

### Describe the bug

For my deployment of Zot I'd like to use an S3 backend. Furthermore, I proxy all my outgoing traffic through an HTTP proxy. However, I have a hard time getting Zot to use the HTTP proxy. Looking at the sourcecode, it seems that the application should respect HTTP_PROXY environment vars, but I cannot get it to work on my side

### To reproduce

1. Configuration
Custom resources:
```yaml
apiVersion: v1
kind: Secret
metadata:
  name: zot-aws-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "VEVTVF9BQ0NFU1NfS0VZX0lE" # Base64 of "TEST_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "VEVTVF9TRUNSRVRfQUNDRVNTX0tFWQ==" # Base64 of "TEST_SECRET_ACCESS_KEY"
---
apiVersion: v1
kind: Service
metadata:
  name: squid-service
  labels:
    app: squid
spec:
  ports:
  - port: 3128
  selector:
    app: squid
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: ubuntu/squid:edge
        ports:
        - containerPort: 3128
          name: squid
          protocol: TCP
        volumeMounts:
        - name: squid-config-volume
          mountPath: /etc/squid/squid.conf
          subPath: squid.conf
      volumes:
        - name: squid-config-volume
          configMap:
            name: squid-config
            items:
            - key: squid
              path: squid.conf
---
apiVersion: v1
data:
  squid: "acl localnet src 0.0.0.1-0.255.255.255\t# RFC 1122 \"this\" network (LAN)\nacl
    localnet src 10.0.0.0/8\t\t# RFC 1918 local private network (LAN)\nacl localnet
    src 100.64.0.0/10\t\t# RFC 6598 shared address space (CGN)\nacl localnet src 169.254.0.0/16
    \t# RFC 3927 link-local (directly plugged) machines\nacl localnet src 172.16.0.0/12\t\t#
    RFC 1918 local private network (LAN)\nacl localnet src 192.168.0.0/16\t\t# RFC
    1918 local private network (LAN)\nacl localnet src fc00::/7       \t# RFC 4193
    local private network range\nacl localnet src fe80::/10      \t# RFC 4291 link-local
    (directly plugged) machines\nacl SSL_ports port 443\nacl Safe_ports port 80\t\t#
    http\nacl Safe_ports port 21\t\t# ftp\nacl Safe_ports port 443\t\t# https\nacl
    Safe_ports port 70\t\t# gopher\nacl Safe_ports port 210\t\t# wais\nacl Safe_ports
    port 1025-65535\t# unregistered ports\nacl Safe_ports port 280\t\t# http-mgmt\nacl
    Safe_ports port 488\t\t# gss-http\nacl Safe_ports port 591\t\t# filemaker\nacl
    Safe_ports port 777\t\t# multiling http\nacl CONNECT method CONNECT\nhttp_access
    deny !Safe_ports\nhttp_access deny CONNECT !SSL_ports\nhttp_access allow localhost
    manager\nhttp_access deny manager\nhttp_access allow localhost\nhttp_access allow
    localnet\nhttp_access deny all\nhttp_port 3128\ncoredump_dir /var/spool/squid\nrefresh_pattern
    ^ftp:\t\t1440\t20%\t10080\nrefresh_pattern ^gopher:\t1440\t0%\t1440\nrefresh_pattern
    -i (/cgi-bin/|\\?) 0\t0%\t0\nrefresh_pattern \\/(Packages|Sources)(|\\.bz2|\\.gz|\\.xz)$
    0 0% 0 refresh-ims\nrefresh_pattern \\/Release(|\\.gpg)$ 0 0% 0 refresh-ims\nrefresh_pattern
    \\/InRelease$ 0 0% 0 refresh-ims\nrefresh_pattern \\/(Translation-.*)(|\\.bz2|\\.gz|\\.xz)$
    0 0% 0 refresh-ims\nrefresh_pattern .\t\t0\t20%\t4320\nlogfile_rotate 0\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: squid-config
```
Helm values:
```yaml
replicaCount: 1
service:
  type: ClusterIP
mountConfig: true
configFiles: 
  config.json: |-
    {
        "distSpecVersion": "1.0.1-dev",
        "storage": {
            "rootDirectory": "/tmp/zot",
            "dedupe": false,
            "storageDriver": {
                "name": "s3",
                "rootdirectory": "/zot",
                "region": "eu-west-1",
                "bucket": "org.example.test-repo",
                "encrypt": true,
                "secure": true,
                "skipverify": true
            }
        },
        "http": {
            "address": "0.0.0.0",
            "port": "5000"
        },
        "log": {
            "level": "trace"
        }
    }
image:
  repository: ghcr.io/project-zot/zot-linux-amd64
  tag: "v1.4.3"
env:
- name: AWS_ACCESS_KEY_ID
  valueFrom:
    secretKeyRef:
      name: zot-aws-secret
      key: AWS_ACCESS_KEY_ID
- name: AWS_SECRET_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: zot-aws-secret
      key: AWS_SECRET_ACCESS_KEY
- name: HTTP_PROXY
  value: "http://squid-service.default.svc.cluster.local:3128"
- name: http_proxy
  value: "http://squid-service.default.svc.cluster.local:3128"
- name: HTTPS_PROXY
  value: "http://squid-service.default.svc.cluster.local:3128"
- name: https_proxy
  value: "http://squid-service.default.svc.cluster.local:3128"
```
2. Apply resources and helm chart
3. Run
```
% kubectl run test-$RANDOM --rm -i -t --image=alpine -- ash
If you don't see a command prompt, try pressing enter.
/ # wget http://zot.default.svc.cluster.local:5000/v2/_catalog
Connecting to zot.default.svc.cluster.local:5000 (10.97.204.23:5000)
```
4. Check logs of Squid proxy
```
% kubectl get pods
NAME                                READY   STATUS             RESTARTS      AGE
squid-deployment-768656f657-zg588   1/1     Running            0             5m
zot-856cb7d78-5ppbm                 1/1     Running            0             4m
% kubectl logs squid-deployment-768656f657-zg588
```

### Expected behavior

The squid logs should show the zot registry perform a `CONNECT` request to `s3.eu-west-1.amazonaws.com`. Instead, the squid logs show no activity.

### Additional context

Performed on a fresh minikube instance. TCP dumps show zot resolving the `s3.eu-west-1.amazonaws.com`, and trying to connect to there directly:
```
07:34:55.764880 IP zot-856cb7d78-m4hdh.49895 > kube-dns.kube-system.svc.cluster.local.53: 1239+ [1au] AAAA? s3.eu-west-1.amazonaws.com.cluster.local. (69)
07:34:55.764909 IP zot-856cb7d78-m4hdh.45298 > kube-dns.kube-system.svc.cluster.local.53: 15235+ [1au] A? s3.eu-west-1.amazonaws.com.cluster.local. (69)
07:34:55.765333 IP zot-856cb7d78-m4hdh.60081 > kube-dns.kube-system.svc.cluster.local.53: 62357+ [1au] AAAA? s3.eu-west-1.amazonaws.com. (55)
07:34:55.765389 IP zot-856cb7d78-m4hdh.60709 > kube-dns.kube-system.svc.cluster.local.53: 29910+ [1au] A? s3.eu-west-1.amazonaws.com. (55)
07:34:55.862853 IP zot-856cb7d78-m4hdh.42940 > s3-eu-west-1.amazonaws.com.443: Flags [S], seq 949395523, win 64240, options [mss 1460,sackOK,TS val 1046646611 ecr 0,nop,wscale 7], length 0
07:34:55.867403 IP zot-856cb7d78-m4hdh.56505 > kube-dns.kube-system.svc.cluster.local.53: 18224+ PTR? 83.57.218.52.in-addr.arpa. (43)
```
