### ISSUE TITLE
[Bug]: unable to pull with partial private images

### ISSUE THREAD

**Issue by aritas1** [project-zot/zot#1917]
### zot version

v2.0.0-rc6

### Describe the bug

If the registry is configured to be partial private the `/v2/` endpoint returns a 200 status code.

Some clients will test on `/v2/` and only send Authorization headers if they see a 40x response.

In my case, docker 24.0.x and watchtower are no longer able to pull images.

### To reproduce

image: ghcr.io/project-zot/zot-linux-amd64:v2.0.0-rc6

config.yaml

```
distspecversion: 1.1.0-dev
http:
  address: 0.0.0.0
  port: 8080
  # externalUrl: "https://registry.example.com"  # as of v2.0.0-rc7
  #realm: zot
  auth:
    #faildelay: 5
    faildelay: 1
    htpasswd:
      path: /config/htpasswd
    openid:
      providers:
        dex:
          issuer: "https://sso.zitadel.com"
          clientid: zot@zitadel
          clientsecret: secret
          scopes:
          - openid
          - email
  accessControl:
    adminPolicy:
      users:
      - admin
      actions:
      - read
      - create
      - update
      - delete
      - detectManifestCollision
    repositories:
      "**":
        defaultPolicy:
        - read
        - create
      "public/**":
        anonymousPolicy:
        - read
log:
  level: info
storage:
  rootdirectory: /data/zot
  dedupe: true
  gc: true
extensions:
  metrics:
    enable: true
    prometheus:
      path: "/metrics_silly"
  search:
    enable: true
    cve:
      updateInterval: 24h
  ui:
    enable: true
  mgmt:
    enable: true
```

### Additional context

For some extra context/test results see the comment [here](https://github.com/project-zot/zot/issues/1914#issuecomment-1754831976).

This may be a issues for the clients but should be tracked in the docs?
