### ISSUE TITLE
[Bug]:Kubernetes probe access failed with 403 when anonymous access is disable

### ISSUE THREAD

**Issue by Jean-Daniel** [project-zot/zot#2087]
### zot version

2.0.0-rc7

### Describe the bug

I'm trying to deploy not into Kubernetes, but if I restrict the access to authenticated users only, the readiness and liveness probes fail with 403 access denied errors.

Being forced to open the repository anonymous access to be able to deploy it in Kubernetes is a show stopper in our case.
There should be a way to allows anonymous read access only on the health endpoint, but as it uses the path `/v2`, there is no way to allow access to the probe while limiting access to root resources.

### To reproduce

1. Configuration
```yaml
http:
  address: "0.0.0.0"
  port: "5000"
  auth: { … }

  accessControl:
    repositories:
      "**":
        defaultPolicy: [ "read", "write", "update", "delete" ]
        anonymousPolicy: []
```

2. Behavior

The pod fails to start as the readiness probe and liveness probe always returns 403.

**Comment by Jean-Daniel** [comment]
I finally found a way that seems to work.

```yaml
http:
  address: "0.0.0.0"
  port: "5000"
  auth: { … }

  accessControl:
    repositories:
      "**":
        defaultPolicy: [ "read", "write", "update", "delete" ]
        anonymousPolicy: []
      "":
        anonymousPolicy: [ "read" ]
```
