### ISSUE TITLE
[Feat]: sync only specified architecture / operating system images

### ISSUE THREAD

**Issue by deric** [project-zot/zot#2122]
### Is your feature request related to a problem? Please describe.

Would it be possible to synchronize only a subset `OS/architecture` images?

### Describe the solution you'd like

Support configuration of synchronized architectures / OS, e.g.:
```yaml
  extensions:
    sync:
      enable: true
      registries:
        - urls:
            - https://registry.k8s.io
           architecture:
             - amd64
            os:
             - linux
```

### Describe alternatives you've considered

It might be possible to filter out architecture based on tags, if the upstream repo uses consistent tags.

### Additional context

Currently all architectures/OSes are synchronized.
```
REPOSITORY    TAG       OS/ARCH         DIGEST      SIGNED      SIZE        
k8s.io/pause  3.8       *               a9627f21    false       853MB       
                        linux/amd64     8a9e1be3    false       308kB       
                        linux/arm/v7    9a28d3e8    false       206kB       
                        linux/arm64     d895231c    false       265kB       
                        linux/ppc64le   4c69178e    false       357kB       
                        linux/s390x     02052591    false       254kB       
                        windows/amd64   dfbedbf6    false       270MB       
                        windows/amd64   637963cd    false       274MB       
                        windows/amd64   4b935553    false       308MB
```
