### ISSUE TITLE
[Bug]: sync: remote repo doesn't support _catalog

### ISSUE THREAD

**Issue by deric** [project-zot/zot#2136]
### zot version

v2.0.0-rc7

### Describe the bug

When mirroring k8s registry, the logs are full of errors like this:

```
{"level":"info","goroutine":66,"caller":"zotregistry.io/zot/pkg/extensions/sync/service.go:441","time":"2023-12-10T15:56:08.508935531Z","message":"getting available client"}
{"level":"error","errorType":"*errors.errorString","remote registry":"https://registry.k8s.io","error":"_catalog is not supported\n","goroutine":66,"caller":"zotregistry.io/zot/pkg/extensions/sync/service.go:187","time":"2023-12-10T15:56:08.55788001Z","message":"error while getting repositories from remote registry"}
{"level":"error","component":"scheduler","error":"_catalog is not supported\n","goroutine":66,"caller":"zotregistry.io/zot/pkg/scheduler/scheduler.go:311","time":"2023-12-10T15:56:08.558002147Z","message":"scheduler: error while executing generator"}
```
registry.k8s.io intentionally doesn't support `GET v2/_catalog` call
```
$ curl -L -XGET https://registry.k8s.io/v2/_catalog
_catalog is not supported
```
see https://github.com/kubernetes/registry.k8s.io/pull/164

### To reproduce

```yaml
  extensions:
    sync:
      enable: true
      registries:
        - urls:
            - https://registry.k8s.io
          onDemand: true
          maxRetries: 3
          retryDelay: 5m
          pollInterval: 6h
          tlsVerify: true
```

### Expected behavior

Silently ignore unsupported call (or add option to ignore fetching `_catalog`)
