### ISSUE TITLE
[Bug]: `failed to get state: securecookie: the value is not valid`

### ISSUE THREAD

**Issue by AndersBennedsgaard** [project-zot/zot#2526]
### zot version

v2.1.0-rc2 (default in the Helm chart)

### Describe the bug

When I set up OIDC auth with Dex yesterday, it was working fine. But when I tried to access our Zot instance this morning, I was met with `failed to get state: securecookie: the value is not valid`. I have a hard time figuring out where the issue comes from, since the only relevant log I can find is:

```text
{"level":"info","module":"http","component":"session","clientIP":"<client-ip>:57554","method":"GET","path":"/zot/auth/callback/oidc?code=<code>&state=<state>","statusCode":401,"latency":"0s","bodySize":58,"headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8"],"Accept-Encoding":["gzip, deflate, br, zstd"],"Accept-Language":["en-US,en;q=0.5"],"Cookie":["statecookie=<state-cookie>; state=<state>"],"Priority":["u=1"],"Referer":["<external-url>/"],"Sec-Fetch-Dest":["document"],"Sec-Fetch-Mode":["navigate"],"Sec-Fetch-Site":["cross-site"],"Sec-Fetch-User":["?1"],"Te":["trailers"],"Upgrade-Insecure-Requests":["1"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0"],"X-Envoy-Expected-Rq-Timeout-Ms":["15000"],"X-Envoy-External-Address":["<ip>"],"X-Forwarded-For":["<ip>"],"X-Forwarded-Proto":["https"],"X-Request-Id":["58079f48-8fc9-4b15-b122-6d89873acba5"],"X-Request-Start":["t=1720077531.100"]},"goroutine":175,"caller":"zotregistry.dev/zot/pkg/api/session.go:132","time":"2024-07-04T07:18:51.101298721Z","message":"HTTP API"}
```

It seems that the cookie key is generated here:

https://github.com/project-zot/zot/blob/002ff05f6e5ab3870aca75e616e8a4ed9b4a5c68/pkg/api/authn.go#L684

The issue might also come from the fact that a random key is generated on startup, which would invalidate the cookies created from other instances of Zot (I run multiple replicas of Zot on Kubernetes, so the different instances have different cookies, and they can restart at random points in time):

https://github.com/project-zot/zot/blob/002ff05f6e5ab3870aca75e616e8a4ed9b4a5c68/pkg/api/cookiestore.go#L85

The recommended way of handling these keys are using fixed keys specified by the user. Perhaps through an environment variable: https://github.com/gorilla/sessions/issues/16#issuecomment-392795038

### To reproduce

I use the following config:

```yaml
storage:
  rootDirectory: /var/lib/registry
  dedupe: false
  storageDriver:
    name: s3
    regionendpoint: http://minio.minio.svc.cluster.local:9000
    region: somewhere # bogus value, but required
    bucket: zot
    skipverify: true
    secure: false
    rootDirectory: /tmp/zot
  gc: true
  gcDelay: 1h
  gcInterval: 24h
log:
  level: debug
http:
  address: 0.0.0.0
  port: "5000"
  externalUrl: <external-url>
  auth:
    openid:
      providers:
        oidc:
          name: OIDC
          issuer: <dex-url>
          clientid: <client-id>
          clientsecret: <client-secret>
          keypath: ""
          scopes:
            - openid
            - profile
            - email
            - groups
  accessControl:
    repositories:
      '**':
        defaultPolicy:
          - read
          - create
          - write
          - update
          - delete
        anonymousPolicy: []
extensions:
  ui:
    enable: true
  search:
    enable: true
  sync:
    enable: true
    credentialsFile: /credentials/credentials.json
    downloadDir: /tmp/sync # has to be specified when using remote storage
    registries:
      # expose ghcr.io/<org>/<repo> under <zot>/ghcr.io/<org>/<repo>
      - urls:
        - https://ghcr.io
        onDemand: true
        tlsVerify: true
        onlySigned: false
        content:
          - prefix: "**"
            destination: ghcr.io

  metrics:
    enable: true
    prometheus:
      path: /metrics
```

It runs two replicas in a Kubernetes cluster.

Other than that, I am not sure how to reproduce. I expect that the above configuration would work if you tried, since it worked for me at first. The issue started after some time.

### Expected behavior

I can log in using OIDC or basic auth

Edit: I tested it without basic auth, and it still didn't work. I updated the above to reflect this
