### ISSUE TITLE
[Bug]: Sync extension panic

### ISSUE THREAD

**Issue by AndersBennedsgaard** [project-zot/zot#2527]
### zot version

v2.1.0-rc2

### Describe the bug

I have set up sync to ghcr.io, but whenever I run something like `helm pull oci://<zot-url>/ghcr.io/grafana/helm-charts/grafana --version 8.0.2` the sync extension panics with:

```text
{"level":"info","params":{"distSpecVersion":"1.1.0","GoVersion":"go1.22.3","Commit":"v2.1.0-rc2-a4b6892a9c276de41e4858e89774c07032410993","ReleaseTag":"v2.1.0-rc2","BinaryType":"-imagetrust-lint-metrics-mgmt-profile-scrub-search-sync-ui-userprefs","Storage":{"RootDirectory":"/var/lib/registry","Dedupe":false,"RemoteCache":false,"GC":true,"Commit":false,"GCDelay":3600000000000,"GCInterval":86400000000000,"Retention":{"DryRun":false,"Delay":0,"Policies":null},"StorageDriver":{"bucket":"zot","name":"s3","region":"somewhere","regionendpoint":"http://minio.minio.svc.cluster.local:9000","rootdirectory":"/tmp/zot","secure":false,"skipverify":true},"CacheDriver":null,"SubPaths":null},"HTTP":{"Address":"0.0.0.0","ExternalURL":"<registry-url>","Port":"5000","AllowOrigin":"","TLS":null,"Auth":{"FailDelay":0,"HTPasswd":{"Path":"/user-credentials/.htpasswd"},"LDAP":null,"Bearer":null,"OpenID":{"Providers":{"oidc":{"Name":"OIDC","ClientID":"<client-id>","ClientSecret":"<client-secret>","KeyPath":"","Issuer":"<issuer-url>","Scopes":["openid","profile","email","groups"]}}},"APIKey":true},"AccessControl":{"repositories":{"**":{"Policies":null,"DefaultPolicy":["read","create","write","update","delete"],"AnonymousPolicy":]}},"AdminPolicy":{"Users":null,"Actions":null,"Groups":null},"Groups":null,"Metrics":{"Users":["prometheus"]}},"Realm":"","Ratelimit":null},"Log":{"Level":"debug","Output":"","Audit":""},"Extensions":{"Search":{"Enable":true,"CVE":null},"Sync":{"Enable":true,"CredentialsFile":"/credentials/credentials.json","DownloadDir":"/tmp/sync","Registries":[{"URLs":["https://ghcr.io"],"PollInterval":0,"Content":[{"Prefix":"<repo>/**","Tags":null,"Destination":"","StripPrefix":false}],"TLSVerify":true,"OnDemand":true,"CertDir":"","MaxRetries":null,"RetryDelay":null,"OnlySigned":false},{"URLs":["https://ghcr.io"],"PollInterval":0,"Content":[{"Prefix":"<repo>/**","Tags":null,"Destination":"<repo-name>","StripPrefix":true}],"TLSVerify":true,"OnDemand":true,"CertDir":"","MaxRetries":null,"RetryDelay":null,"OnlySigned":false},{"URLs":["https://ghcr.io"],"PollInterval":0,"Content":[{"Prefix":"**","Tags":null,"Destination":"ghcr.io","StripPrefix":false}],"TLSVerify":true,"OnDemand":true,"CertDir":"","MaxRetries":null,"RetryDelay":null,"OnlySigned":false}]},"Metrics":{"Enable":true,"Prometheus":{"Path":"/metrics"}},"Scrub":null,"Lint":null,"UI":{"Enable":true},"Mgmt":null,"APIKey":null,"Trust":null},"scheduler":null,"cluster":null},"goroutine":1,"caller":"zotregistry.dev/zot/pkg/api/controller.go:259","time":"2024-07-10T09:58:48.478767479Z","message":"configuration settings"}
{"level":"info","cpus":8,"max. open files":1048576,"listen backlog":"1024","max. inotify watches":"12288","goroutine":1,"caller":"zotregistry.dev/zot/pkg/api/controller.go:128","time":"2024-07-10T09:58:48.478904258Z","message":"runtime params"}
{"level":"info","component":"metadb","goroutine":1,"caller":"zotregistry.dev/zot/pkg/meta/parse.go:28","time":"2024-07-10T09:58:48.673137762Z","message":"parsing storage and initializing"}
{"level":"info","component":"metadb","goroutine":1,"caller":"zotregistry.dev/zot/pkg/meta/parse.go:82","time":"2024-07-10T09:58:48.709610406Z","message":"successfully initialized"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_search.go:55","time":"2024-07-10T09:58:48.709972463Z","message":"cve config not provided, skipping cve-db update"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_scrub.go:47","time":"2024-07-10T09:58:48.710016361Z","message":"scrub config not provided, skipping scrub"}
{"level":"debug","goroutine":27,"caller":"zotregistry.dev/zot/pkg/storage/imagestore/imagestore.go:322","time":"2024-07-10T09:58:48.713145842Z","message":"empty rootDir"}
{"level":"debug","component":"scheduler","generator":"GCTaskGenerator","goroutine":27,"caller":"zotregistry.dev/zot/pkg/scheduler/scheduler.go:478","time":"2024-07-10T09:58:48.713184122Z","message":"generator is done"}
{"level":"info","component":"dedupe","goroutine":27,"caller":"zotregistry.dev/zot/pkg/storage/common/common.go:849","time":"2024-07-10T09:58:48.824190082Z","message":"no repositories found in storage, finished."}
{"level":"debug","component":"scheduler","generator":"DedupeTaskGenerator","goroutine":27,"caller":"zotregistry.dev/zot/pkg/scheduler/scheduler.go:478","time":"2024-07-10T09:58:48.82422044Z","message":"generator is done"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/api/routes.go:121","time":"2024-07-10T09:58:49.187432853Z","message":"access control is being enabled"}
{"level":"warn","goroutine":1,"caller":"zotregistry.dev/zot/pkg/debug/swagger/swagger_disabled.go:20","time":"2024-07-10T09:58:49.188636755Z","message":"skipping enabling swagger because given zot binary doesn't include this feature, please build a binary that does so"}
{"level":"warn","goroutine":1,"caller":"zotregistry.dev/zot/pkg/debug/gqlplayground/gqlplayground_disabled.go:17","time":"2024-07-10T09:58:49.188694043Z","message":"skipping enabling graphql playground extension because given zot binary doesn't include this feature, please build a binary that does so"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_metrics.go:31","time":"2024-07-10T09:58:49.188800823Z","message":"setting up metrics routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_search.go:84","time":"2024-07-10T09:58:49.188934603Z","message":"setting up search routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_search.go:104","time":"2024-07-10T09:58:49.189037987Z","message":"finished setting up search routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_image_trust.go:30","time":"2024-07-10T09:58:49.189096692Z","message":"skip enabling the image trust routes as the config prerequisites are not met"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_mgmt.go:94","time":"2024-07-10T09:58:49.189144382Z","message":"setting up mgmt routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_mgmt.go:107","time":"2024-07-10T09:58:49.189214504Z","message":"finished setting up mgmt routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_userprefs.go:38","time":"2024-07-10T09:58:49.189297759Z","message":"setting up user preferences routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_userprefs.go:48","time":"2024-07-10T09:58:49.189352889Z","message":"finished setting up user preferences routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_ui.go:69","time":"2024-07-10T09:58:49.189394736Z","message":"setting up ui routes"}
{"level":"info","goroutine":1,"caller":"zotregistry.dev/zot/pkg/extensions/extension_ui.go:95","time":"2024-07-10T09:58:49.190451433Z","message":"finished setting up ui routes"}
{"level":"info","module":"http","component":"session","clientIP":"10.68.2.2:59994","method":"HEAD","path":"/v2/ghcr.io/grafana/helm-charts/grafana/manifests/8.0.2","statusCode":401,"latency":"0s","bodySize":253,"headers":{"Accept":["application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*"],"User-Agent":["Helm/3.15.2"],"X-Envoy-Expected-Rq-Timeout-Ms":["15000"],"X-Envoy-External-Address":["<external-ip>"],"X-Forwarded-For":["<x-forwarded-for>"],"X-Forwarded-Proto":["https"],"X-Request-Id":["<request-id>"],"X-Request-Start":["t=1720605536.292"]},"goroutine":176,"caller":"zotregistry.dev/zot/pkg/api/session.go:132","time":"2024-07-10T09:58:56.294509284Z","message":"HTTP API"}
{"level":"info","identity":"admin","goroutine":176,"caller":"zotregistry.dev/zot/pkg/api/authn.go:143","time":"2024-07-10T09:58:56.428520333Z","message":"user profile successfully set"}
{"level":"info","repository":"ghcr.io/grafana/helm-charts/grafana","reference":"8.0.2","goroutine":176,"caller":"zotregistry.dev/zot/pkg/api/routes.go:1939","time":"2024-07-10T09:58:56.428682403Z","message":"trying to get updated image by syncing on demand"}
{"level":"info","goroutine":204,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:507","time":"2024-07-10T09:58:56.428749942Z","message":"getting available client"}
{"level":"info","remote":"https://ghcr.io","repository":"ghcr.io/grafana/helm-charts/grafana","reference":"8.0.2","goroutine":204,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:300","time":"2024-07-10T09:58:56.520906013Z","message":"will not sync image, filtered out by content"}
{"level":"info","goroutine":204,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:507","time":"2024-07-10T09:58:56.520934699Z","message":"getting available client"}
{"level":"info","remote":"https://ghcr.io","repository":"ghcr.io/grafana/helm-charts/grafana","reference":"8.0.2","goroutine":204,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:300","time":"2024-07-10T09:58:56.611652953Z","message":"will not sync image, filtered out by content"}
{"level":"info","goroutine":204,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:507","time":"2024-07-10T09:58:56.611689206Z","message":"getting available client"}
{"level":"info","remote":"https://ghcr.io","repository":"ghcr.io/grafana/helm-charts/grafana","reference":"8.0.2","goroutine":204,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:309","time":"2024-07-10T09:58:56.717013281Z","message":"syncing image"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x130 pc=0x5b4fed573545]

goroutine 204 [running]:
zotregistry.dev/zot/pkg/extensions/sync.OciLayoutStorageImpl.GetImageReference({{{0x0?, 0x0?}, 0x0?}, 0xc001ff0780?}, {0xc00343f549, 0x23}, {0xc00343f577, 0x5})
    zotregistry.dev/zot/pkg/extensions/sync/oci_layout.go:43 +0x65
zotregistry.dev/zot/pkg/extensions/sync.(*DestinationRegistry).GetImageReference(0xc001f8c370?, {0xc00343f549?, 0x23?}, {0xc00343f577?, 0x5?})
    zotregistry.dev/zot/pkg/extensions/sync/destination.go:88 +0x26
zotregistry.dev/zot/pkg/extensions/sync.(*BaseService).syncTag(0xc002a26788, {0x5b4ff0a21438, 0xc0025507b0}, {0xc00343f549, 0x23}, {0xc00343f551, 0x1b}, {0xc00343f577, 0x5})
    zotregistry.dev/zot/pkg/extensions/sync/service.go:455 +0xb67
zotregistry.dev/zot/pkg/extensions/sync.(*BaseService).SyncImage(0xc002a26788, {0x5b4ff0a21438, 0xc0025507b0}, {0xc00343f549, 0x23}, {0xc00343f577, 0x5})
    zotregistry.dev/zot/pkg/extensions/sync/service.go:311 +0x24c
zotregistry.dev/zot/pkg/extensions/sync.(*BaseOnDemand).syncImage(0xc001f62090, {0x5b4ff0a21438, 0xc0025507b0}, {0xc00343f549, 0x23}, {0xc00343f577, 0x5}, 0xc0034104e0)
    zotregistry.dev/zot/pkg/extensions/sync/on_demand.go:122 +0x18e
created by zotregistry.dev/zot/pkg/extensions/sync.(*BaseOnDemand).SyncImage in goroutine 176
    zotregistry.dev/zot/pkg/extensions/sync/on_demand.go:76 +0x3bc
Stream closed EOF for zot/zot-857bcc76d4-4jjqx (zot)
```

I enabled remote S3 storage with MinIO yesterday when it began, but I don't see a reason why that should matter.

The line which fails is:

https://github.com/project-zot/zot/blob/a4b6892a9c276de41e4858e89774c07032410993/pkg/extensions/sync/oci_layout.go#L43

I guess that `localImageStore` is `nil` because the `oci.storeController.GetImageStore(repo)` on the line before has returned a `nil` interface, but I am not sure this is the case

### To reproduce

The configuration I use:

```yaml
storage:
  rootDirectory: /var/lib/registry
  dedupe: false
  storageDriver:
    name: s3
    regionendpoint: http://minio.minio.svc.cluster.local:9000
    region: us-east-2
    bucket: zot
    skipverify: true
    secure: false
  gc: true
  gcDelay: 1h
  gcInterval: 24h
log:
  level: debug
http:
  address: 0.0.0.0
  port: "5000"
  externalUrl: <external-url>
  auth:
    htpasswd:
      path: /user-credentials/.htpasswd
    openid:
      providers:
        oidc:
          name: OIDC
          issuer: <dex-url>
          clientid: <client-id>
          clientsecret: <client-secret>
          keypath: ""
          scopes:
            - openid
            - profile
            - email
            - groups
  accessControl:
    metrics:
      users:
        - prometheus
    repositories:
      '**':
        defaultPolicy:
          - read
          - create
          - write
          - update
          - delete
        anonymousPolicy: []
extensions:
  ui:
    enable: true
  search:
    enable: true
  sync:
    enable: true
    credentialsFile: /credentials/credentials.json
    downloadDir: /tmp/sync # has to be specified when using remote storage
    registries:
      # expose ghcr.io/<org>/<repo> under <zot>/ghcr.io/<org>/<repo>
      - urls:
        - https://ghcr.io
        onDemand: true
        tlsVerify: true
        onlySigned: false
        content:
          - prefix: "**"
            destination: ghcr.io

  metrics:
    enable: true
    prometheus:
      path: /metrics
```

### Expected behavior

No nil-pointer dereference issues
