### ISSUE TITLE
[Feat]: Persist API keys

### ISSUE THREAD

**Issue by AndersBennedsgaard** [project-zot/zot#2591]
### Is your feature request related to a problem? Please describe.

Whenever we restart Zot, user API keys are seemingly removed. This makes it such that users have to recreate their keys to interact with Zot through automation.

### Describe the solution you'd like

It seems like the API keys are stored in the cache service: https://github.com/project-zot/zot/blob/main/pkg/api/routes.go#L2106

However, it doesn't really make sense to store something like API keys in a temporary cache, since these are long-lived (which caches are not, by definition)

Instead, the API keys should be stored in some long-lived storage, like S3

**Comment by AndersBennedsgaard** [comment]
According to https://zotregistry.dev/v2.1.0/articles/storage/?h=bolt#cache-drivers:

> A cache driver is used to store duplicate blobs when dedupe is enabled. zot supports database caching using BoltDB as the cache driver for local filesystems and DynamoDB for remote filesystems.

To me, it sounds like BoltDB is used as a cache, and not a long-lived data store. Is that not correct?

My storage configuration looks like:

```yaml
storage:
  rootDirectory: /var/lib/registry
  dedupe: false
  storageDriver:
    name: s3
    regionendpoint: http://minio.minio.svc.cluster.local:9000
    region: us-east-2
    bucket: zot
    skipverify: false
    secure: false
  gc: true
  gcDelay: 1h
  gcInterval: 24h
```

I have not set the `/var/lib/registry` directory up to be persistent on restart, or shared between my two Zot replicas. I guess I have to do that?
