### ISSUE TITLE
[Feat]: LDAP user filter

### ISSUE THREAD

**Issue by vooon** [project-zot/zot#2924]
### Is your feature request related to a problem? Please describe.

I want to filter disabled users, or by some other fields.
LDAP has the feature to write a filter for that, but seems Zot do not have it in the config.

### Describe the solution you'd like

Add userFilter field, so i can write something like that:

```yaml
http:
  auth:
    ldap:
      userFilter: "(&(objectClass=inetorgperson)(!(nsaccountlock=TRUE))(!(userClass=Bot))(!(sn=Notifier)))"
```

### Describe alternatives you've considered

None, as filtering do not need any code (except passing string) on the client side.
