### ISSUE TITLE
[Bug]: Docker pull fails to pull from restricted path if anonymous access allowed on the other path

### ISSUE THREAD

**Issue by vooon** [project-zot/zot#2928]
### zot version

2.1.3-rc1 (master)

### Describe the bug

So, there a some base images, that i want any clients to be able to pull, but rest of the images - only for logged users.
Without login I'm able to pull `repo.tld/base/foo:bar`, but not `repo.tld/service/baz:latest`, that's expected.
Once i've done `podman login repo.tld` and `docker login repo.tld`, i can `podman pull  repo.tld/service/baz:latest`, but not the docker one!
```
# docker --debug -l debug pull repo.tld/service/baz:latest
time="2025-01-30T16:00:03Z" level=debug msg="otel error" error="1 errors occurred detecting resource:\n\t* conflicting Schema URL: https://opentelemetry.io/schemas/1.21.0 and https://opentelemetry.io/schemas/1.26.0"
Error response from daemon: unauthorized: authentication required
```

From the Zot log i see that it does:
1. `GET /v2/`, without auth, 200 OK
2.  `HEAD /v2/service/baz/manifests/latest`, 401
3. end

If there no anonymous access allowed flow:
1. `GET /v2/`, - 401
2.  `HEAD /v2/service/baz/manifests/latest`, with auth - 200 OK
3. loading layers ...

### To reproduce

1. Configuration

```yaml
http:
  address: 0.0.0.0
  port: 443
  tls:
    cert: /etc/zot/tls.crt
    key: /etc/zot/tls.key
  auth:
    accessControl:
      repositories:
        "**": {defaultPolicy: [read]}
        "base/**": {anonymousPolicy: [read]}
```

2. Client tool used: `docker/27.5.1 go/go1.22.11 git-commit/4c9b3b0`

### Expected behavior

Docker pulls protected images when there also anonymous access allowed for some other path.
