### ISSUE TITLE
[Feat]: Domain name alias

### ISSUE THREAD

**Issue by vooon** [project-zot/zot#2985]
### Is your feature request related to a problem? Please describe.

Docker cannot add a subpath to caching mirror url (like podman do), so it needs a dedicated domain name.
It'll be nice to be able to route some name to subpath, e.g:

```yaml
http:
  realm: https://zot.local
  mapping:
    - domain: docker.zot.local
      path: /docker.io
extensions:
  sync:
    registries:
      - urls: [https://index.docker.io]
        onDemand: true
        content:
          - prefix: "**"
          - destination: "/docker.io"
```

So then i can set `/etc/docker/daemon.json` to:
```json
{
  "registry-mirrors": ["https://docker.zot.local"]
}
```

### Describe alternatives you've considered

Now a Nginx with a bunch of rewrite rules have used.

**Comment by rchincha** [comment]
@vooon 

Can you shed more light on your deployment and use case?

> Docker cannot add a subpath to caching mirror url (like podman do)

**Comment by vooon** [comment]
@rchincha Zot works as a cache to docker.io, but serving it on the subpath `/docker.io`. It also works as a cache for other registries, so i cannot just run it for `/`.

A Podman supports that natively with [registries.conf][1], so i have something like that:
```toml
unqualified-search-registries = ["docker.io"]

[[registry]]
location = "docker.io"

[[registry.mirror]]
location = "zot.local/docker.io"
```

But Docker cannot add anything to path, so it needs a dedicated name, which do that aliasing inside.

So, let's say, i want to pull `library/mariadb:latest`, podman automatically will pull `zot.local/docker.io/library/mariadb:latest`, but docker - only `<mirror>/library/mariadb:latest` (mirror cannot have path).

Nginx can do the trick by rewriting the path, but i'd prefer if i can drop it entirely...

[1]: https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md
