### ISSUE TITLE
[Bug]: downloadDir bloat

### ISSUE THREAD

**Issue by maxemontio** [project-zot/zot#2995]
### zot version

v2.1.2

### Describe the bug

We have an instance of zot running in docker on an ec2 vm as a mirror with s3 storage driver for two k8s clusters.
Suddenly we find out that downloadDir (sync extension) is full and not cleaned automatically. At the same time we see a constantly high network usage around 1gb/s

![Image](https://github.com/user-attachments/assets/7a941060-9da0-4ec0-9741-7b1dbcf13bf4)

You can see drop of used space around 16 hours, this was a manual cleanup.

If you look closer to network usage, you can see distinct patterns:

![Image](https://github.com/user-attachments/assets/f4b17e9e-6fe5-4dff-b664-46a8584ac2ce)

This load was found out to be caused by zot communicating with s3, but zot's metrics doesn't show a lot of active pulls made by clusters, what makes me think this is something that zot does by itself.

In addition to that during that strange behaviour there is a problem with metrics - some counters look like to be reset:

![Image](https://github.com/user-attachments/assets/27ee02c2-7bd8-40af-acb6-f85cd9e9a2c8)

We use zot for k8s, so we had to put it's endpoint to containerd config. But we need zot to mirror 3 registries, but zot can't serve access to them on different ports, only paths, but containerd can't work with paths, only ports. So we had to put zot behind a nginx proxy which listens several ports and proxies requests to zot entrypoints.

zot config:
```
distSpecVersion: 1.0.1
storage:
  rootDirectory: "{{ data_path }}"
  dedupe: false
  gc: true
  gcDelay: "3h"
  retention:
    policies:
      - repositories:
          - "**"
        deleteUntagged: false
        keepTags:
          patterns:
            - ".*"
          mostRecentlyPulledCount: 13
  storageDriver:
    name: s3
    region: us-east-1
    bucket: "{{ s3_cache_bucket }}"
    secure: true
http:
  address: 127.0.0.1
  externalURL: "https://{{ cname_dns }}"
  port: 8443
  realm: zot
  auth:
    htpasswd:
      path: /opt/zot/basic_auth
  accessControl:
    metrics:
      users: ["metrics"]
    repositories:
      "**":
        anonymousPolicy:
          - read
    adminPolicy:
      groups:
        - admin
      actions:
        - read
        - create
        - update
        - delete
extensions:
  scrub:
    enable: true
    interval: "2h"
  search:
    enable: false
  metrics:
    enable: true
    prometheus:
      path: "/metrics"
  ui:
    enable: false
  sync:
    enable: true
    downloadDir: "{{ data_path }}/tmp"
    registries:
      - urls:
          - https://mirror.gcr.io
        content:
          - destination: "/gcr"
            prefix: "**"
            stripPrefix: true
        onDemand: true
        maxRetries: 3
        retryDelay: 5m
      - urls:
          - https://ghcr.io
        content:
          - destination: "/ghcr"
            prefix: "**"
            stripPrefix: true
        onDemand: true
        maxRetries: 3
        retryDelay: 5m
      - urls:
          - https://docker.internal # our local image storage
        content:
          - destination: "/nexus"
            prefix: "**"
            stripPrefix: true
        onDemand: true
        maxRetries: 3
        retryDelay: 5m
```

nginx config:
```
server {
  listen 80;
  server_name {{ cname_dns }};
  return 301 https://$host$request_uri;
}

proxy_set_header  Host $host;
proxy_set_header  X-Real-IP $remote_addr;
proxy_set_header  X-Forwarded-Proto $scheme;
proxy_set_header  X-Forwarded-Port $server_port;
proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;

ssl_session_cache shared:SSL:10m;
ssl_certificate /opt/zot/certs/live/zot_certs/fullchain.pem;
ssl_certificate_key /opt/zot/certs/live/zot_certs/privkey.pem;

client_max_body_size 3G;
proxy_no_cache 1;
proxy_cache_bypass 1;

server {
  listen 443 ssl;
  server_name {{ cname_dns }};

  location / {
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }};
  }
}

server {
  listen 8080 ssl;

  location /v2/ {
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/;
  }

  location ~ ^/v2/(.*)/manifests/(.*){
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/gcr/$1/manifests/$2;
  }

  location ~ ^/v2/(.*)/blobs/(.*) {
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/gcr/$1/blobs/$2;
  }
}

server {
  listen 8081 ssl;

  location /v2/ {
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/;
  }

  location ~ ^/v2/(.*)/manifests/(.*){
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/ghcr/$1/manifests/$2;
  }

  location ~ ^/v2/(.*)/blobs/(.*) {
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/ghcr/$1/blobs/$2;
  }
}

server {
  listen 8082 ssl;

  location /v2/ {
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/;
  }

  location ~ ^/v2/(.*)/manifests/(.*){
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/nexus/$1/manifests/$2;
  }

  location ~ ^/v2/(.*)/blobs/(.*) {
    proxy_pass http://{{ zot_config.http.address }}:{{ zot_config.http.port }}/v2/nexus/$1/blobs/$2;
  }
}
```
Variables are from ansible as we use it to upload configuration and run containers on the instance.

---
So what is that strange behaviour with network and disk space usage? (other peaks on graphs look like a work of the go garbage collector) Is that some sort of misconfiguration or something else? We have two k8s clusters more and one more zot instance to serve them with absolutely the same configuration and there is no problem like that.
