### ISSUE TITLE
[Bug]: Images not being cached

### ISSUE THREAD

**Issue by pieterv-icloud-com** [project-zot/zot#3004]
### zot version

v2.1.2

### Describe the bug

Hi, this is my first time trying zot.

I have zot running with kind in a devcontainer but I am facing some issues.

### To reproduce

1. Configuration

zot is configured as follows:

```
{
  "distSpecVersion": "1.1.0",
  "storage": {
    "rootDirectory": "/tmp/zot",
    "commit": true,
    "dedupe": true,
    "gc": true,
    "gcDelay": "1h",
    "gcInterval": "2h"
  },
  "http": {
    "address": "0.0.0.0",
    "port": "5000",
    "compat": [
      "docker2s2"
    ]
  },
  "log": {
    "level": "debug"
  },
  "extensions": {
    "scrub": {
      "enable": true
    },
    "search": {
      "enable": true
    },
    "ui": {
      "enable": true
    },
    "sync": {
      "enable": true,
      "downloadDir": "/tmp/zot/sync",
      "registries": [
        {
          "urls": [
            "https://k8s.gcr.io",
            "https://docker.io",
            "https://quay.io",
            "https://registry.k8s.io",
            "https://ghcr.io",
            "https://oci.external-secrets.io"
          ],
          "onDemand": true,
          "retryDelay": "5m",
          "onlySigned": false,
          "maxRetries": 100,
          "tlsVerify": true,
          "content": [
            {
              "prefix": "**"
            }
          ]
        }
      ]
    }
  }
}
```

Zot is initialized as follows:

```
#!/bin/bash
set -e

# Initialization script for Zok

# Create a docker container cache
sudo mkdir -p /tmp/kind-registry
sudo chmod 777 /tmp/kind-registry

# Determine the current architecture
zod_version="v2.1.2"
ARCH=$(uname -m)
if [ "$ARCH" == "x86_64" ]; then
  ZOT_IMAGE="ghcr.io/project-zot/zot-linux-amd64:$zod_version"
elif [ "$ARCH" == "aarch64" ] || [ "$ARCH" == "arm64" ]; then
  ZOT_IMAGE="ghcr.io/project-zot/zot-linux-arm64:$zod_version"
else
  echo "Error: Unsupported architecture $ARCH"
  exit 1
fi

# create registry container unless it already exists
reg_name='kind-registry'
reg_port='5001'
ui_port='8080'
if [ "$(docker inspect -f "${reg_name}" 2>/dev/null || true)" != 'true' ]; then
  docker rm -f "${reg_name}" || true
  docker create --name "${reg_name}" --restart=always -p "127.0.0.1:${reg_port}:5000" -p "127.0.0.1:8084:${ui_port}" -v /tmp/kind-registry:/tmp/zot -v $(pwd)/scripts/zot.json:/etc/zot/config.json $ZOT_IMAGE
  docker start "${reg_name}"
fi

# check whether already connected to the network
if [ "$(docker inspect -f='{{json .NetworkSettings.Networks.kind}}' \
"${reg_name}")" = 'null' ]; then
  docker network connect "kind" "${reg_name}"
fi
```

Kind is configured as follows:

```
apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
networking:
  ipFamily: ipv4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."k8s.gcr.io"]
    endpoint = ["http://kind-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."quay.io"]
    endpoint = ["http://kind-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."registry.k8s.io"]
    endpoint = ["http://kind-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["http://kind-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."ghcr.io"]
    endpoint = ["http://kind-registry:5000"]
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."oci.external-secrets.io"]
    endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
  - role: worker
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP  
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-status-update-frequency: "4s"        
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-status-update-frequency: "4s"  
  - role: worker
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-status-update-frequency: "4s"
```

3. Client tool used
4. Seen error

I only have 2 images cached with this configuration:

```
.
├── cache.db
├── ingress-nginx
│   └── kube-webhook-certgen
│       ├── blobs
│       │   └── sha256
│       │       ├── 0bab15eea81d0fe6ab56ebf5fba14e02c4c1775a7f7436fbddd3505add4e18fa
│       │       ├── 0baecf37abeec25aad5f5bb99f3fa20e90f15361468ef5b66fae93e9c8283c3d
│       │       ├── 1240b99db6f5a73d9066cbe47c040bd956a13041a4330be42e1ad2638c3f239c
│       │       ├── 280c45e5adc80ae549eed4849f1858e266bf630606f5afe54b782fc9ae3a6957
│       │       ├── 2fe6cfdfccdad7871233c4dd8fa51aeb7aa06c72765956c86ced0eb6441e005e
│       │       ├── 3214acf345c0cc6bbdb56b698a41ccdefc624a09d6beb0d38b5de0b2303ecaf4
│       │       ├── 3572e0bc50bd4a5c066af9ed663983fe821b0817ab8a915b83dca4441566395a
│       │       ├── 3af676b90ddc3ca1f7e2dca11a4b0fa68ce5dd056ea4160711ffaf0e97a98090
│       │       ├── 4aa0ea1413d37a58615488592a0b827ea4b2e48fa5a77cf707d0e35f025e613f
│       │       ├── 5664b15f108bf9436ce3312090a767300800edbbfd4511aa1a6d64357024d5dd
│       │       ├── 6595b1857d401122cdd3af77beba638a8f34de43870cc7d1ea471a8f0a55459e
│       │       ├── 689c016d44de61c3697472b415cea65ab38f0a1d10e67f22aa753d471a252bc8
│       │       ├── 70af07e19fd3586f8a3b17d6b50edb30c949b03541123d10af74e2250499a2a3
│       │       ├── 7c12895b777bcaa8ccae0605b4de635b68fc32d60fa08f421dc3818bf55ee212
│       │       ├── 7e70a166ac5dbd6f8ac8ac7adf254219958f4987560077eb6dbfc58201f32df2
│       │       ├── 8ee69f337ce76952d2e917f74ff0315fa04d488443a43978c2009474d5d6e347
│       │       ├── 94c85dc77d15d3d1d86748fe35dfbf203146e6a2fc63e1a8c547ff9509ce56e0
│       │       ├── 9aee425378d2c16cd44177dc54a274b312897f5860a8e78fdfda555a0d79dd71
│       │       ├── 9b59c52649da6d40579c88864583ccea8c7d49a4f7eda4b305e3a273e8290328
│       │       ├── a08fb65fab37ae109dbf0d93069ff27d8bd95a4d97541c3cc771e89461ee43b8
│       │       ├── a62778643d563b511190663ef9a77c30d46d282facfdce4f3a7aecc03423c1f3
│       │       ├── a6875f1c3d9293bf7e754924715ee17adc123d8ab0a491903692ed1fd71c7cff
│       │       ├── aaafd456bda110628b2d4ca6296f38731a3aaf0bf7581efae824a41c770a8fc4
│       │       ├── abb2ca65938000dc989d82e4a637c2e0e77ed39ea676b38df8f6e783990fec07
│       │       ├── b03bc4398b60a70ba095d134716df7336d3a163808730fc6d52dd0d424036316
│       │       ├── bc3c0fd4af237cebafeab1caf45335d82b30f9af71a15d9a0d069420226355d4
│       │       ├── bfb59b82a9b65e47d485e53b3e815bca3b3e21a095bd0cb88ced9ac0b48062bf
│       │       ├── d6e05c6379ae47ac0e9a68295ca756a647e4307a73a8aa841fc5d2e1a1d02422
│       │       ├── d94fa90fa27be4f576bd2cd8eafadd18fb2f3f07c1550c89d4c537bc81f42374
│       │       ├── d9ccad1729447eed20bdcb61968374a8a55bebbdd48f1104ba4c2851e6dc821b
│       │       ├── da7816fa955ea24533c388143c78804c28682eef99b4ee3723b548c70148bba6
│       │       ├── df88b8c4dc8fdabf15f6933648335d726f9631cf4e40314e3ca1db576ef133d0
│       │       └── efa9d1d5d3a286c60a7261496166fdf31cec2284dafe7eef7cda89eba2f675d6
│       ├── index.json
│       └── oci-layout
├── meta.db
├── sync
│   ├── ingress-nginx
│   │   ├── controller
│   │   └── kube-webhook-certgen
│   └── kube-state-metrics
│       └── kube-state-metrics
└── test
```

The logs is full of errors saying it cannot find a path and not being able to sync:

```
{"level":"info","repo":"jaegertracing/all-in-one","sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350":"reference","err":"reading manifest sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350 in k8s.gcr.io/jaegertracing/all-in-one: manifest unknown: Requested entity was not found.","component":"sync","goroutine":75992,"caller":"zotregistry.dev/zot/pkg/extensions/sync/on_demand.go:157","time":"2025-03-09T20:00:07.717024961Z","message":"starting routine to copy image, because of error"}
{"level":"error","error":"reading manifest sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350 in k8s.gcr.io/jaegertracing/all-in-one: manifest unknown: Requested entity was not found.","repository":"jaegertracing/all-in-one","reference":"sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350","goroutine":75450,"caller":"zotregistry.dev/zot/pkg/api/routes.go:2093","time":"2025-03-09T20:00:07.717039044Z","message":"failed to sync image"}
{"level":"info","module":"http","component":"session","clientIP":"172.19.0.3:35768","method":"GET","path":"/v2/jaegertracing/all-in-one/manifests/sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350?ns=docker.io","statusCode":404,"latency":"3s","bodySize":229,"headers":{"Accept":["application/vnd.oci.image.manifest.v1+json, */*"],"Accept-Encoding":["zstd;q=1.0, gzip;q=0.8, deflate;q=0.5"],"User-Agent":["containerd/v2.0.2"]},"goroutine":75450,"caller":"zotregistry.dev/zot/pkg/api/session.go:137","time":"2025-03-09T20:00:07.718004211Z","message":"HTTP API"}
{"level":"error","error":": Path not found: /tmp/zot/jaegertracing/all-in-one/blobs/sha256/04f27d735b01e3d413f579f0b66530c0ba9f624ae5ed894fd39e12660a1e09cc","blob":"/tmp/zot/jaegertracing/all-in-one/blobs/sha256/04f27d735b01e3d413f579f0b66530c0ba9f624ae5ed894fd39e12660a1e09cc","goroutine":76046,"caller":"zotregistry.dev/zot/pkg/storage/imagestore/imagestore.go:1487","time":"2025-03-09T20:00:07.999796877Z","message":"failed to stat blob"}
```

```
{"level":"info","repository":"jaegertracing/all-in-one","reference":"sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3","goroutine":74403,"caller":"zotregistry.dev/zot/pkg/api/routes.go:2089","time":"2025-03-09T19:59:58.878255429Z","message":"trying to get updated image by syncing on demand"}
{"level":"info","goroutine":74405,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:508","time":"2025-03-09T19:59:58.878288887Z","message":"getting available client"}
{"level":"info","remote":"https://k8s.gcr.io","repository":"jaegertracing/all-in-one","reference":"sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3","goroutine":74405,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:310","time":"2025-03-09T19:59:59.279527804Z","message":"syncing image"}
{"level":"error","error":"reading manifest sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3 in k8s.gcr.io/jaegertracing/all-in-one: manifest unknown: Requested entity was not found.","repository":"jaegertracing/all-in-one","reference":"sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3","goroutine":74405,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:427","time":"2025-03-09T20:00:02.4410185Z","message":"couldn't get upstream image manifest details"}
{"level":"error","error":"reading manifest sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3 in k8s.gcr.io/jaegertracing/all-in-one: manifest unknown: Requested entity was not found.","repository":"jaegertracing/all-in-one","reference":"sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3","goroutine":74403,"caller":"zotregistry.dev/zot/pkg/api/routes.go:2093","time":"2025-03-09T20:00:02.441144208Z","message":"failed to sync image"}
{"level":"info","repo":"jaegertracing/all-in-one","sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3":"reference","err":"reading manifest sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3 in k8s.gcr.io/jaegertracing/all-in-one: manifest unknown: Requested entity was not found.","component":"sync","goroutine":75027,"caller":"zotregistry.dev/zot/pkg/extensions/sync/on_demand.go:157","time":"2025-03-09T20:00:02.441251958Z","message":"starting routine to copy image, because of error"}
{"level":"info","module":"http","component":"session","clientIP":"172.19.0.3:35756","method":"GET","path":"/v2/jaegertracing/all-in-one/manifests/sha256:34e3d18e0f2eeb9abd9bb53d0dc7abaf2a5b1c884fdca575093af3126811a9d3?ns=docker.io","statusCode":404,"latency":"3s","bodySize":229,"headers":{"Accept":["application/vnd.oci.image.index.v1+json, */*"],"Accept-Encoding":["zstd;q=1.0, gzip;q=0.8, deflate;q=0.5"],"User-Agent":["containerd/v2.0.2"]},"goroutine":74403,"caller":"zotregistry.dev/zot/pkg/api/session.go:137","time":"2025-03-09T20:00:02.441776125Z","message":"HTTP API"}
{"level":"info","repository":"jaegertracing/all-in-one","reference":"sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350","goroutine":75450,"caller":"zotregistry.dev/zot/pkg/api/routes.go:2089","time":"2025-03-09T20:00:04.630126542Z","message":"trying to get updated image by syncing on demand"}
{"level":"info","goroutine":75452,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:508","time":"2025-03-09T20:00:04.630161626Z","message":"getting available client"}
{"level":"info","remote":"https://k8s.gcr.io","repository":"jaegertracing/all-in-one","reference":"sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350","goroutine":75452,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:310","time":"2025-03-09T20:00:05.434958168Z","message":"syncing image"}
{"level":"error","error":"reading manifest sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350 in k8s.gcr.io/jaegertracing/all-in-one: manifest unknown: Requested entity was not found.","repository":"jaegertracing/all-in-one","reference":"sha256:3897d6dd6310b727074bab572b93def00992e9ebf3807ec479099174435fd350","goroutine":75452,"caller":"zotregistry.dev/zot/pkg/extensions/sync/service.go:427","time":"2025-03-09T20:00:07.716846336Z","message":"couldn't get upstream image manifest details"}
```

Is there something wrong with my configuration?

### Expected behavior

I should see additional cached images and no errors.
