### ISSUE TITLE
Can I run pods that pull images from zot?

### ISSUE THREAD

**Issue by TheCodingSheikh** [project-zot/zot#3232]
### zot version

2.1.2
helm values

```yaml
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
persistence: true
pvc:
  create: true
  storage: 100Gi
service:
  type: ClusterIP
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  className: "nginx"
  hosts:
    - host: <registry>
      paths:
        - path: /
  tls:
   - secretName: zot-tls
     hosts:
       - <registry>
```

### Describe the bug
this is the error i get when describing a pod

```
Failed to pull image "<registry>/<image>:v1.03": failed to pull and unpack image "<registry>/<image>:v1.03": failed to resolve reference "<registry>/<image>:v1.03": failed to do request: Head "https://<registry>/v2/<image>/manifests/v1.03": Service Unavailable
```

in some way it is a in issue with crictl, because i can use `docker pull <registry>/<image>:v1.03` and it works fine, but pods trying to pull or using `crictl pull <registry>/<image>:v1.03` i get this issue
### To reproduce

1. Configuration
2. Client tool used
3. Seen error

### Expected behavior

pods can pull images / I can pull with crictl 

### Additional context

- the registry domain is behind ingress nginx
